=== NickRighez/tw_progetto_gnrr/XMLSchema.xsd
<?xml version="1.0" ?>

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http:\\www.dominio.com"
	    xmlns="http:\\www.dominio.com" >
  
  <!-- MODELLO TENDE ALLA VENEZIANA -->
  	<xs:element name="TravelShare" type="TTravelShare" />

  	<xs:complexType name="TTravelShare" >
  		<xs:sequence>
  			<xs:element name="SetUtenti" type="TSetUtenti" />
  			<xs:element name="SetPassaggi" type="TSetPassaggi" />
  			<xs:element name="SetMessaggi" type="TSetMessaggi" />
  			<xs:element name="SetFeedback" type="TSetFeedback" />
  		</xs:sequence>
  	</xs:complexType>

  	<xs:complexType name="TSetUtenti" >
  		<xs:sequence>   
    		<xs:element name="Utente" minOccurs="0" maxOccurs="unbounded" type="TUtente" />
  		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TSetPassaggi" >
    	<xs:sequence>
    		<xs:element name="Passaggio" minOccurs="0" maxOccurs="unbounded" type="TPassaggio" >
    	</xs:sequence>
    </complexType>

    <xs:complexType name="TSetMessaggi" >
 		<xs:sequence>
 			<xs:element name="Conversazione" type="TConversazione" minOccurs="0" maxOccurs="unbounded" />
 		</xs:sequence>
 	</xs:complexType>

 	<xs:complexType name="TSetFeedback" >
 		<xs:sequence>
 			<xs:element name="Feedback" type="TFeedback" minOccurs="0" maxOccurs="unbounded" />
 		</xs:sequence>
 	</xs:complexType>



<!-- ************************************ INIZIO UTENTE ********************* -->
    
    <xs:complexType name="TUtente" >
	  <xs:sequence>
	  	<xs:element name="IDUtente" type="xs:ID" />
	  	<xs:element name="Nome" type="xs:string" />	  
	  	<xs:element name="Cognome" type="xs:string" />	  
	  	<xs:element name="Sesso" type="TSesso" />	  
	  	<xs:element name="AnnoNascita" type="TAnnoNascita" />	  
	  	<xs:element name="Telefono" type="TTelefono" />	  
	  	<xs:element name="Password" type="TPassword" />  	  
	  	<xs:element name="Email" type="TEmail" />
	  	<xs:element name="Profilo" type="TProfilo" />
	  </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TSesso" >
      <xs:restriction base="xs:string">
	<xs:enumeration value="M" />
	<xs:enumeration value="F" />
      </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TAnnoNascita">
      <xs:restriction base="xs:integer">
	<xs:length value="4" />
      </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TTelefono" >
     <xs:restriction base="xs:string">
	<xs:pattern value="[0-9]{3}-[0-9]{7}" />
      </xs:restriction>
    </xs:simpleType>
	
    <xs:simpleType name="TPassword" >
      <xs:restriction base="xs:integer">
	<xs:length value="4" />
      </xs:restriction>
    </xs:simpleType>
	
    <xs:complexType name="TProfilo" >
      <xs:sequence>
		<xs:element name="NumFeedbRicevuti" type="xs:integer" default="0" />	
		<xs:element name="NumPassaggiOff" type="xs:integer" default="0" />	
		<xs:element name="NumpassaggiPart" type="xs:integer" default="0" />
		<xs:choice>
		  <xs:sequence>
		    <xs:element name="Valutazione" type="FullValutazione" />
		    <xs:element name="Preferenze" type="Preferenze" />
		  </xs:sequence>
		  <xs:sequence>  
		    <xs:element name="Valutazione" type="FullValutazione" />
		  </xs:sequence>
		</xs:choice>		
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Preferenze">
      <xs:sequence>
		<xs:element name="Chiacchere" type="GradoPreferenze" />
		<xs:element name="Musica" type="GradoPreferenze" />
		<xs:element name="Animali" type="GradoPreferenze" />
		<xs:element name="Fumatore" type="GradoPreferenze" />
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Valutazione">
      	<xs:sequence>
			<xs:element name="PunteggioMedio" type="GradoValutazione" default="0" />
			<xs:element name="Compagnia" type="GradoValutazione" default="0" />
			<xs:element name="Puntualita" type="GradoValutazione" default="0" />
      	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="FullValutazione">
      <xs:complexContent>
		<xs:extension base="Valutazione">
		  	<xs:sequence>
		    <xs:element name="Pulizia" type="GradoValutazione" default="0" />
		    <xs:element name="Guida" type="GradoValutazione" default="0" />
		</xs:sequence>
		</xs:extension>
      </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="GradoValutazione">
      <xs:restriction base="xs:integer">
		<xs:minInclusive value="0" />
		<xs:maxInclusive value="4" />
      </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="GradoPreferenze">
      <xs:restriction base="xs:string">
		<xs:enumeration value="Mai" />
		<xs:enumeration value="Occasionalmente" />
		<xs:enumeration value="Sempre" />
      </xs:restriction>
    </xs:simpleType>    
 <!-- ****************** FINE UTENTE   ************** -->  
    
    
<!-- *************************************** INIZIO PASSAGGIO *************************************************************** -->   
    
    <xs:complexType type="TPassaggio" >
	  <xs:sequence>	  
	  	<xs:element name="Conducente" type="xs:IDREF" />	  
	  	<xs:element name="PrezzoTot" type="xs:integer" />	  
	  	<xs:element name="PostiTot" type="xs:integer" />	  
	  	<xs:element name="Dettagli" type="xs:string" />     
	  	<xs:element name="Itinerario" type="TItinerario" />	
	  	<xs:element name="Bacheca" type="TBacheca" />  
	  </xs:sequence>
    </xs:complexType>


    <xs:complexType name="TItinerario">
      <xs:sequence>		
		<xs:element name="Partenza" type="T_Tratta" />	
		
		<xs:choice minOccurs="0">
	  		<xs:sequence>
	    		<xs:element name="Tappa1" type="T_Tratta" />
	  		</xs:sequence>		  		  
	  		<xs:sequence>
			    <xs:element name="Tappa1" type="T_Tratta" />
			    <xs:element name="Tappa2" type="T_Tratta" />
			</xs:sequence>		  
			<xs:sequence>
			    <xs:element name="Tappa1" type="T_Tratta" />
			    <xs:element name="Tappa2" type="T_Tratta" />
			    <xs:element name="Tappa3" type="T_Tratta" />  
			</xs:sequence>
		</xs:choice>
	
		<xs:element name="Arrivo" type="T_Tratta" />	      
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_Tratta">
      <xs:sequence>
	  <xs:element name="Prezzo" type="xs:integer" />
	  <xs:element name="PostiDisp" type="xs:integer" />
	  <xs:element name="Data" type="xs:date" />
	  <xs:element name="Ora" type="xs:time" />
	  <xs:element name="Provincia" type="xs:string" />
	  <xs:element name="Comune" type="xs:string" />
	  <xs:element name="Prenotazioni" type="TPrenotazioni" />
      </xs:sequence>
    </xs:complexType>    

    <xs:complexType name="TPrenotazioni" >
      <xs:sequence>
		<xs:element name="Utente" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>	

    <xs:complexType name="TBacheca" >
    	<xs:sequence>
    		<xs:element name="MessaggioBacheca" type="TMessaggioBacheca" minOccurs="0" maxOccurs="unbounded" />
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="TMessaggioBacheca">
    	<xs:sequence>
    		<xs:element name="Mittente" type="xs:IDREF" />
    		<xs:element name="Data" type="xs:date" />
 			<xs:element name="Ora" type="xs:time" />
 			<xs:element name="Testo" type="xs:string" />
 			<xs:element name="Risposte" type="TBacheca" minOccurs="0" />
 		</xs:sequence>
 	</xs:complexType>
    	
 <!--   **************** FINE PASSAGGIO **************   -->	      
  

 <!--  ***************** INIZIO MESSAGGI 1vs1 ************************************************************************************************   -->

 	<xs:complexType name="TConversazione ">
 		<xs:attribute name="IDMitt" type="xs:IDREF" />
 		<xs:attribute name="IDDest" type="xs:IDREF" />
 		<xs:sequence>
 			<xs:element name="Messaggio" type="TMessaggio" minOccurs="0" maxOccurs="unbounded" />
 		</xs:sequence>
 	</xs:complexType>

 	<xs:complexType name="TMessaggio" >
 		<xs:sequence>
 			<xs:element name="Mittente" type="xs:IDREF" />
 			<xs:element name="Data" type="xs:date" />
 			<xs:element name="Ora" type="xs:time" />
 			<xs:element name="Testo" type="xs:string" />
 		</xs:sequence>
 	</xs:complexType>

<!--   **************** FINE MESSAGGI 1vs1 **************   -->

<!--   **************** INIZIO FEEDBACK  **************************************************** -->

	<xs:complexType name="TFeedback" >
		<xs:attribute name="IDMitt" type="xs:IDREF" />
 		<xs:attribute name="IDDest" type="xs:IDREF" />
 		<xs:sequence>
 			<xs:element name="Passaggio" type="xs:IDREF" />
 			<xs:element name="Commento" type="xs:string" />
 		</xs:sequence>
 		<xs:choice>
  			<xs:element name="ValutazionePasseg" type="Valutazione" />
 			<xs:element name="ValutazioneConduc" type="FullValutazione" />
 		</xs:choice>
 	</xs:complexType>

</xs:schema>

=== NickRighez/tw_progetto_gnrr/Versione x server/data/TravelShare.xml
<?xml version="1.0" encoding="utf-8"?>
<ts:TravelShare xmlns:ts="http://www.dominio.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.dominio.com XMLSchema.xsd">
  <!--  ***************************************************************   SET UTENTI   ************************** -->
  <SetUtenti>
    <Utente>
      <Username>utente_uno</Username>
      <Email>utente_uno@gmail.com</Email>
      <Nome>Giovanni</Nome>
      <Cognome>Sanna</Cognome>
      <DescrizionePers>Mi piace ascoltare musica durante i viaggi</DescrizionePers>
      <Sesso>maschio</Sesso>
      <AnnoNascita>1990</AnnoNascita>
      <Password>11111111</Password>
      <Profilo>
        <NumFeedbRicevuti>0</NumFeedbRicevuti>
        <NumPassaggiOff>1</NumPassaggiOff>
        <NumPassaggiPart>2</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>0</PunteggioMedio>
          <Compagnia>0</Compagnia>
          <Puntualita>0</Puntualita>
          <Pulizia>0</Pulizia>
          <Guida>0</Guida>
        </Valutazione>
        <Auto>citroen</Auto>
        <Patente>2000</Patente>
        <Preferenze>
          <Chiacchiere>0</Chiacchiere>
          <Musica>1</Musica>
          <Animali>1</Animali>
          <Fumatore>1</Fumatore>
        </Preferenze>
      </Profilo>
      <Notifiche>
        <EsitoPrenotaz Passaggio="v1" Esito="Accettata" Partenza="3" Arrivo="4" />
      </Notifiche>
    </Utente>
    <Utente>
      <Username>utente_due</Username>
      <Email>utente_due@gmail.com</Email>
      <Nome>Paola</Nome>
      <Cognome>Martin</Cognome>
      <DescrizionePers />
      <Sesso>femmina</Sesso>
      <AnnoNascita>1990</AnnoNascita>
      <Password>11111111</Password>
      <Profilo>
        <NumFeedbRicevuti>1</NumFeedbRicevuti>
        <NumPassaggiOff>1</NumPassaggiOff>
        <NumPassaggiPart>0</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>3</PunteggioMedio>
          <Compagnia>3</Compagnia>
          <Puntualita>3</Puntualita>
          <Pulizia>3</Pulizia>
          <Guida>3</Guida>
        </Valutazione>
        <Auto>jaguark</Auto>
        <Patente>2000</Patente>
        <Preferenze>
          <Chiacchiere>2</Chiacchiere>
          <Musica>2</Musica>
          <Animali>1</Animali>
          <Fumatore>0</Fumatore>
        </Preferenze>
      </Profilo>
      <Notifiche>
        
      </Notifiche>
    </Utente>
    <Utente>
      <Username>utente_tre</Username>
      <Email>utente_tre@gmail.com</Email>
      <Nome>Nicolò</Nome>
      <Cognome>Rigatò</Cognome>
      <Sesso>maschio</Sesso>
      <AnnoNascita>1993</AnnoNascita>
      <Password>11111111</Password>
      <Profilo>
        <NumFeedbRicevuti>0</NumFeedbRicevuti>
        <NumPassaggiOff>0</NumPassaggiOff>
        <NumPassaggiPart>0</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>0</PunteggioMedio>
          <Compagnia>0</Compagnia>
          <Puntualita>0</Puntualita>
          <Pulizia>0</Pulizia>
          <Guida>0</Guida>
        </Valutazione>
      </Profilo>
      <Notifiche>
        <NuovoMessaggio Mittente="utente_uno" />
      </Notifiche>
    </Utente>
    <Utente>
      <Username>utente_quattro</Username>
      <Email>utente_quattro@gmai.com</Email>
      <Nome>Marié</Nome>
      <Cognome>Vinàs</Cognome>
      <Sesso>maschio</Sesso>
      <AnnoNascita>1990</AnnoNascita>
      <Password>11111111</Password>
      <Profilo>
        <NumFeedbRicevuti>0</NumFeedbRicevuti>
        <NumPassaggiOff>0</NumPassaggiOff>
        <NumPassaggiPart>1</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>0</PunteggioMedio>
          <Compagnia>0</Compagnia>
          <Puntualita>0</Puntualita>
          <Pulizia>0</Pulizia>
          <Guida>0</Guida>
        </Valutazione>
      </Profilo>
      <Notifiche>
      </Notifiche>
    </Utente>
    <Utente>
      <Username>utente_cinque</Username>
      <Email>utente_cinque@gmail.com</Email>
      <Nome>Riccardo</Nome>
      <Cognome>Ardossi</Cognome>
      <Sesso>maschio</Sesso>
      <AnnoNascita>1990</AnnoNascita>
      <Password>11111111</Password>
      <Profilo>
        <NumFeedbRicevuti>0</NumFeedbRicevuti>
        <NumPassaggiOff>0</NumPassaggiOff>
        <NumPassaggiPart>1</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>0</PunteggioMedio>
          <Compagnia>0</Compagnia>
          <Puntualita>0</Puntualita>
          <Pulizia>0</Pulizia>
          <Guida>0</Guida>
        </Valutazione>
      </Profilo>
      <Notifiche>
      </Notifiche>
    </Utente>
    <Utente>
      <Username>utente_sei</Username>
      <Email>utente_sei@gmail.com</Email>
      <Nome>giovanni</Nome>
      <Cognome>Curie</Cognome>
      <Sesso>maschio</Sesso>
      <AnnoNascita>1990</AnnoNascita>
      <Password>11111111</Password>
      <Profilo>
        <NumFeedbRicevuti>0</NumFeedbRicevuti>
        <NumPassaggiOff>0</NumPassaggiOff>
        <NumPassaggiPart>0</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>0</PunteggioMedio>
          <Compagnia>0</Compagnia>
          <Puntualita>0</Puntualita>
          <Pulizia>0</Pulizia>
          <Guida>0</Guida>
        </Valutazione>
      </Profilo>
      <Notifiche>
    </Notifiche>
    </Utente>
  </SetUtenti>
  <!--  ***************************************************************   SET PASSAGGI   ************************** -->
  <SetPassaggi>
    <Passaggio Passato="no">
      <IDViaggio>v1</IDViaggio>
      <Conducente>utente_due</Conducente>
      <PrezzoTot>22</PrezzoTot>
      <PostiTot>4</PostiTot>
      <Dettagli>ciaociaociao</Dettagli>
      <Itinerario>
        <Partenza Numero="0">
          <PostiDisp>4</PostiDisp>
          <Data>2016-11-16</Data>
          <Ora>12:00:00</Ora>
          <Luogo>padova</Luogo>
          <Prenotazioni />
        </Partenza>
        <Tappa Numero="1">
          <PostiDisp>3</PostiDisp>
          <Data>2016-11-16</Data>
          <Ora>14:12:00</Ora>
          <Luogo>verona</Luogo>
          <Prenotazioni>
            <Utente>utente_cinque</Utente>
          </Prenotazioni>
        </Tappa>
        <Tappa Numero="2">
          <PostiDisp>2</PostiDisp>
          <Data>2016-11-16</Data>
          <Ora>16:24:00</Ora>
          <Luogo>vicenza</Luogo>
          <Prenotazioni>
            <Utente>utente_quattro</Utente>
            <Utente>utente_cinque</Utente>
          </Prenotazioni>
        </Tappa>
        <Tappa Numero="3">
          <PostiDisp>3</PostiDisp>
          <Data>2016-11-16</Data>
          <Ora>18:36:00</Ora>
          <Luogo>rovigo</Luogo>
          <Prenotazioni>
            <Utente>utente_uno</Utente>
          </Prenotazioni>
        </Tappa>
        <Arrivo Numero="4">
          <PostiDisp>0</PostiDisp>
          <Data>2016-11-16</Data>
          <Ora>23:00:00</Ora>
          <Luogo>milano</Luogo>
          <Prenotazioni />
        </Arrivo>
      </Itinerario>
      <Bacheca>
        <ConversazioneBacheca User1="utente_cinque" User2="utente_due">
          <Messaggio>
            <Mittente>utente_cinque</Mittente>
            <Data>2016-11-03</Data>
            <Ora>12:54:01</Ora>
            <Testo>ciao conducente utente due
</Testo>
          </Messaggio>
        </ConversazioneBacheca>
        <ConversazioneBacheca User1="utente_uno" User2="utente_due">
          <Messaggio>
            <Mittente>utente_uno</Mittente>
            <Data>2016-11-03</Data>
            <Ora>13:03:55</Ora>
            <Testo>ciaoooooooo sono l utente uno</Testo>
          </Messaggio>
        </ConversazioneBacheca>
      </Bacheca>
    </Passaggio>
    <Passaggio Passato="no">
      <IDViaggio>v2</IDViaggio>
      <Conducente>utente_uno</Conducente>
      <PrezzoTot>11</PrezzoTot>
      <PostiTot>3</PostiTot>
      <Itinerario>
        <Partenza Numero="0">
          <PostiDisp>3</PostiDisp>
          <Data>2016-11-06</Data>
          <Ora>12:00:00</Ora>
          <Luogo>Padova</Luogo>
          <Prenotazioni />
        </Partenza>
        <Arrivo Numero="4">
          <PostiDisp>0</PostiDisp>
          <Data>2016-11-06</Data>
          <Ora>15:00:00</Ora>
          <Luogo>Milano</Luogo>
          <Prenotazioni />
        </Arrivo>
      </Itinerario>
      <Bacheca />
    </Passaggio>
  </SetPassaggi>
  <!--  ***************************************************************   SET MESSAGGI   ************************** -->
  <SetMessaggi>
    <Conversazione User1="utente_uno" User2="utente_due">
      <Messaggio Letto="si">
        <Mittente>utente_uno</Mittente>
        <Data>2016-11-03</Data>
        <Ora>13:05:54</Ora>
        <Testo>ciao</Testo>
      </Messaggio>
      <Messaggio Letto="si">
        <Mittente>utente_uno</Mittente>
        <Data>2016-11-03</Data>
        <Ora>13:06:04</Ora>
        <Testo>ciaociao</Testo>
      </Messaggio>
      <Messaggio Letto="si">
        <Mittente>utente_uno</Mittente>
        <Data>2016-11-04</Data>
        <Ora>12:17:00</Ora>
        <Testo>ggggg</Testo>
      </Messaggio>
      <Messaggio Letto="si">
        <Mittente>utente_uno</Mittente>
        <Data>2016-11-04</Data>
        <Ora>12:17:56</Ora>
        <Testo>nnnnn</Testo>
      </Messaggio>
    </Conversazione>
    <Conversazione User1="utente_uno" User2="utente_tre">
      <Messaggio Letto="no">
        <Mittente>utente_uno</Mittente>
        <Data>2016-11-05</Data>
        <Ora>15:35:58</Ora>
        <Testo>ciao</Testo>
      </Messaggio>
    </Conversazione>
  </SetMessaggi>
  <!--  ***************************************************************   SET FEEDBACK   ************************** -->
  <SetFeedback>
  </SetFeedback>
</ts:TravelShare>
