=== NickRighez/tw_progetto_gnrr/file_sito/XMLSchema.xsd
<?xml version="1.0" ?>

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
      targetNamespace="http://www.dominio.com"
      xmlns="http://www.dominio.com"
       > 
  
<!-- 

******  MODIFICA PREFERENZE : preferenze fumare e animali da cambiare in due valori SI/NO


-->


  <!-- MODELLO TENDE ALLA VENEZIANA -->
    <xs:element name="TravelShare" type="TTravelShare" />

    <xs:complexType name="TTravelShare" >
      <xs:sequence>
        <xs:element name="SetUtenti" type="TSetUtenti" />
        <xs:element name="SetPassaggi" type="TSetPassaggi" />
        <xs:element name="SetMessaggi" type="TSetMessaggi" />
        <xs:element name="SetFeedback" type="TSetFeedback" />
      </xs:sequence>
	<xs:attribute name="numeroUtenti" type="xs:integer" default="0" />
    </xs:complexType>

    <xs:complexType name="TSetUtenti" >
      <xs:sequence>   
        <xs:element name="Utente" minOccurs="0" maxOccurs="unbounded" type="TUtente" />
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TSetPassaggi" >
      <xs:sequence>
        <xs:element name="Passaggio" minOccurs="0" maxOccurs="unbounded" type="TPassaggio" />
      </xs:sequence>
    <xs:attribute name="numeroViaggi" type="xs:integer" default="0" />
    </xs:complexType>

    <xs:complexType name="TSetMessaggi" >
    <xs:sequence>
      <xs:element name="Conversazione" type="TConversazione" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TSetFeedback" >
    <xs:sequence>
      <xs:element name="Feedback" type="TFeedback" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>



<!-- ************************************ INIZIO UTENTE ********************* -->
    
    <xs:complexType name="TUtente" >
      <xs:sequence>
        <xs:element name="Username" type="xs:ID" />
        <xs:element name="Email" type="TEmail" />
        <xs:element name="Nome" type="xs:string" />   
        <xs:element name="Cognome" type="xs:string" />   
        <xs:element name="DescrizionePers" type="xs:string" minOccurs="0"/> 
        <xs:element name="Sesso" type="TSesso" />   
        <xs:element name="AnnoNascita" type="TAnno" />   
        <xs:element name="Password" type="xs:string" />
        <xs:element name="Profilo" type="TProfilo" />
        <xs:element name="Notifiche" type="TNotifiche" />
      </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TSesso" >
      <xs:restriction base="xs:string">
        <xs:enumeration value="M" />
        <xs:enumeration value="F" />
        <xs:enumeration value="maschio" />
        <xs:enumeration value="femmina" />
      </xs:restriction>
    </xs:simpleType>

  <xs:simpleType name="TEmail">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/> <!-- verificare l'espressione -->
    </xs:restriction>
  </xs:simpleType>
    
    <xs:simpleType name="TAnno">
      <xs:restriction base="xs:integer">
        <xs:pattern value="[1-2][0-9][0-9][0-9]" />
      </xs:restriction>
    </xs:simpleType>
  
    <xs:simpleType name="TPassword" >
      <xs:restriction base="xs:string">
      <!-- pattern per pasword -->
      </xs:restriction>
    </xs:simpleType>
  
    <xs:complexType name="TProfilo" >
      <xs:sequence>
          <xs:element name="NumFeedbRicevuti" type="xs:integer" default="0" />  
          <xs:element name="NumPassaggiOff" type="xs:integer" default="0" />  
          <xs:element name="NumPassaggiPart" type="xs:integer" default="0" />
          <xs:element name="Valutazione" type="TFullValutazione" />
          <xs:element name="Auto" type="xs:string" minOccurs="0" />
          <xs:element name="Patente" type="TAnno" minOccurs="0" />
          <xs:element name="Preferenze" type="TPreferenze" minOccurs="0" /> 
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TNotifiche" >
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="NuovoMessaggio" type="TNuovoMessaggio" />
        <xs:element name="NuovoMessaggioBacheca" type="TNuovoMessaggioBacheca" />
        <xs:element name="FeedDaRilasciare" type="TFeedDaRilasciare" />
        <xs:element name="RichiestaPrenotaz" type="TRichiestaPrenotaz" />
        <xs:element name="AccettazionePrenotaz" type="TAccettazionePrenotaz" />
      </xs:choice>
    </xs:complexType>

    <xs:complexType name="TNuovoMessaggio" >
      <xs:attribute name="Mittente" type="xs:IDREF" />
      <xs:attribute name="Destinatario" type="xs:IDREF" />
    </xs:complexType>

    <xs:complexType name="TNuovoMessaggioBacheca" >
      <xs:attribute name="Mittente" type="xs:IDREF" />
      <xs:attribute name="Passaggio" type="xs:IDREF" />
    </xs:complexType>

    <xs:complexType name="TFeedDaRilasciare" >
      <xs:attribute name="Destinatario" type="xs:IDREF" />
      <xs:attribute name="Passaggio" type="xs:IDREF" />
    </xs:complexType>

    <xs:complexType name="TRichiestaPrenotaz" >
      <xs:attribute name="Mittente" type="xs:IDREF" />
      <xs:attribute name="Passaggio" type="xs:IDREF" />
    </xs:complexType>

    <xs:complexType name="TAccettazionePrenotaz" >
      <xs:attribute name="Passaggio" type="xs:IDREF" />
    </xs:complexType>

    <xs:complexType name="TPreferenze">
      <xs:sequence>
        <xs:element name="Chiacchiere" type="TGradoPreferenze" />
        <xs:element name="Musica" type="TGradoPreferenze" />
        <xs:element name="Animali" type="TGradoPreferenze" />
        <xs:element name="Fumatore" type="TGradoPreferenze" />
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TValutazione">
        <xs:sequence>
          <xs:element name="PunteggioMedio" type="xs:decimal" default="0" />
          <xs:element name="Compagnia" type="TGradoValutazione" default="0" />
          <xs:element name="Puntualita" type="TGradoValutazione" default="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TFullValutazione">
      <xs:complexContent>
        <xs:extension base="TValutazione">
          <xs:sequence>
            <xs:element name="Pulizia" type="TGradoValutazione" default="0" />
            <xs:element name="Guida" type="TGradoValutazione" default="0" />
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="TGradoValutazione">
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0" />
        <xs:maxInclusive value="4" />
      </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="TGradoPreferenze">
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0" />
        <xs:enumeration value="1" />
        <xs:enumeration value="2" />
      </xs:restriction>
    </xs:simpleType>    
 <!-- ****************** FINE UTENTE   ************** -->  
    
    
<!-- *************************************** INIZIO PASSAGGIO *************************************************************** -->   
    
    <xs:complexType name="TPassaggio" >
      <xs:sequence>   
        <xs:element name="IDViaggio" type="xs:ID" />
        <xs:element name="Conducente" type="xs:IDREF" />    
        <xs:element name="PrezzoTot" type="xs:integer" />   
        <xs:element name="PostiTot" type="xs:integer" />    
        <xs:element name="Dettagli" type="xs:string" minOccurs="0"/>     
        <xs:element name="Itinerario" type="TItinerario" /> 
        <xs:element name="Bacheca" type="TBacheca" />  
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TItinerario">
      <xs:sequence>   
        <xs:element name="Partenza" type="T_Tratta" />
        <xs:element name="Tappa" type="T_Tratta" minOccurs="0" maxOccurs="3" /> 
        <xs:element name="Arrivo" type="T_Tratta" />        
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_Tratta">
      <xs:sequence>
        <!--<xs:element name="Prezzo" type="xs:integer" />    ############ MODIFICA ############ -->
        <xs:element name="PostiDisp" type="xs:integer" />
        <xs:element name="Data" type="xs:date" />
        <xs:element name="Ora" type="xs:time" />
        <xs:element name="Luogo" type="xs:string" />  <!-- ######### MODIFICATO ##############Ã  -->
        <xs:element name="Prenotazioni" type="TPrenotazioni" /> 
      </xs:sequence>
      <xs:attribute name="Numero" type="xs:integer" />
    </xs:complexType>    

    <xs:complexType name="TPrenotazioni" >
      <xs:sequence>
        <xs:element name="Utente" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType> 

    <xs:complexType name="TBacheca" >
      <xs:sequence>
        <xs:element name="ConversazioneBacheca" type="TConversazione" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
<!--
    <xs:complexType name="TMessaggioBacheca">
      <xs:attribute name="Identificativo" type="xs:string" />
      <xs:sequence>
        <xs:element name="Mittente" type="xs:IDREF" />
        <xs:element name="Data" type="xs:date" />
        <xs:element name="Ora" type="xs:time" />
        <xs:element name="Testo" type="xs:string" />
        <xs:element name="Risposte" type="TBacheca" minOccurs="0" />
    </xs:sequence>
  </xs:complexType> -->
      
 <!--   **************** FINE PASSAGGIO **************   -->        
  

 <!--  ***************** INIZIO MESSAGGI 1vs1 ************************************************************************************************   -->

  <xs:complexType name="TConversazione">
    <xs:sequence>
      <xs:element name="Messaggio" type="TMessaggio" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="User1" type="xs:IDREF" />
    <xs:attribute name="User2" type="xs:IDREF" />
  </xs:complexType>

  <xs:complexType name="TMessaggio" >
    <xs:sequence>
      <xs:element name="Mittente" type="xs:IDREF" />
      <xs:element name="Data" type="xs:date" />
      <xs:element name="Ora" type="xs:time" />
      <xs:element name="Testo" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Letto" type="TMessLetto" use='optional'/>
  </xs:complexType>

  <xs:simpleType name="TMessLetto">
    <xs:restriction base="xs:string">
      <xs:enumeration value="si"/>
      <xs:enumeration value="no" />
    </xs:restriction>
  </xs:simpleType>

<!--   **************** FINE MESSAGGI 1vs1 **************   -->

<!--   **************** INIZIO FEEDBACK  **************************************************** -->

  <xs:complexType name="TFeedback" >
    <xs:sequence>
      <xs:element name="Passaggio" type="xs:IDREF" />
      <xs:element name="Commento" type="xs:string" />
      <xs:choice>
          <xs:element name="ValutazionePasseg" type="TValutazione" />
          <xs:element name="ValutazioneConduc" type="TFullValutazione" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="IDMitt" type="xs:IDREF" />
    <xs:attribute name="IDDest" type="xs:IDREF" />
  </xs:complexType>

</xs:schema>

=== NickRighez/tw_progetto_gnrr/file_sito/provaXML.xml
<?xml version="1.0" encoding="utf-8"?>
<ts:TravelShare xmlns:ts="http://www.dominio.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.dominio.com XMLSchema.xsd">
  <!--  ***************************************************************   SET UTENTI   ************************** -->
  <SetUtenti>
    <Utente>
      <Username>u1</Username>
      <Email>sannagiovanni9@hhh.it</Email>
      <Nome>gio</Nome>
      <Cognome>sanna</Cognome>
      <Sesso>femmina</Sesso>
      <AnnoNascita>1966</AnnoNascita>
      <Password>333</Password>
      <Profilo>
        <NumFeedbRicevuti>0</NumFeedbRicevuti>
        <NumPassaggiOff>0</NumPassaggiOff>
        <NumPassaggiPart>0</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>0</PunteggioMedio>
          <Compagnia>0</Compagnia>
          <Puntualita>0</Puntualita>
          <Pulizia>0</Pulizia>
          <Guida>0</Guida>
        </Valutazione>
        <Auto>dbbbb</Auto>
        <Patente>1966</Patente>
        <Preferenze>
          <Chiacchiere>2</Chiacchiere>
          <Musica>2</Musica>
          <Animali>1</Animali>
          <Fumatore>0</Fumatore>
        </Preferenze>
      </Profilo>
      <Notifiche>
      </Notifiche>
    </Utente>
    <Utente>
      <Username>u2</Username>
      <Email>pincopal@gmail.com</Email>
      <Nome>Mario</Nome>
      <Cognome>Bianchi</Cognome>
      <Sesso>M</Sesso>
      <AnnoNascita>1990</AnnoNascita>
      <Password>333</Password>
      <Profilo>
        <NumFeedbRicevuti>0</NumFeedbRicevuti>
        <NumPassaggiOff>0</NumPassaggiOff>
        <NumPassaggiPart>0</NumPassaggiPart>
        <Valutazione>
          <PunteggioMedio>0</PunteggioMedio>
          <Compagnia>0</Compagnia>
          <Puntualita>0</Puntualita>
          <Pulizia>0</Pulizia>
          <Guida>0</Guida>
        </Valutazione>
      </Profilo>
      <Notifiche>
      </Notifiche>
    </Utente>
  </SetUtenti>
  <!--  ***************************************************************   SET PASSAGGI   ************************** -->
  <SetPassaggi>
    <Passaggio>
      <IDViaggio>v1</IDViaggio>
      <Conducente>u1</Conducente>
      <!-- l utente conducente deve avere definito le sue preferenze -->
      <PrezzoTot>15</PrezzoTot>
      <PostiTot>4</PostiTot>
      <Dettagli>Max un bagaglio medio</Dettagli>
      <Itinerario>
        <Partenza Numero="0">
          <PostiDisp>4</PostiDisp>
          <Data>2016-04-24</Data>
          <Ora>12:00:00</Ora>
          <Luogo>Padova Piove di sacco</Luogo>
          <Prenotazioni>

				</Prenotazioni>
        </Partenza>
        <Tappa Numero="1">
          <PostiDisp>3</PostiDisp>
          <!-- il num di posti disponibili dev essere coerente con : PostiTot-count(Prenotazioni/Utente) -->
          <Data>2016-04-24</Data>
          <Ora>15:00:00</Ora>
          <Luogo>Vicenza</Luogo>
          <Prenotazioni>
            <Utente>u2</Utente>
          </Prenotazioni>
        </Tappa>
        <Arrivo Numero="4">
          <PostiDisp>4</PostiDisp>
          <Data>2016-04-24</Data>
          <Ora>17:00:00</Ora>
          <Luogo>Padova</Luogo>
          <Prenotazioni>
				</Prenotazioni>
        </Arrivo>
      </Itinerario>
      <Bacheca>
        <!-- non ci sono messaggi per questa bacheca -->
        <ConversazioneBacheca User1="u2" User2="u1">
          <Messaggio>
            <Mittente>u2</Mittente>
            <Data>2016-08-08</Data>
            <Ora>11:33:06</Ora>
            <Testo>ciaociao</Testo>
          </Messaggio>
          <Messaggio>
            <Mittente>u1</Mittente>
            <Data>2016-08-08</Data>
            <Ora>11:33:40</Ora>
            <Testo>ciaociao</Testo>
          </Messaggio>
        </ConversazioneBacheca>
      </Bacheca>
    </Passaggio>
    <Passaggio>
      <IDViaggio>v2</IDViaggio>
      <Conducente>u1</Conducente>
      <!-- l utente conducente deve avere definito le sue preferenze -->
      <PrezzoTot>15</PrezzoTot>
      <PostiTot>4</PostiTot>
      <Dettagli>Max un bagaglio medio</Dettagli>
      <Itinerario>
        <Partenza Numero="0">
          <PostiDisp>4</PostiDisp>
          <Data>2016-04-24</Data>
          <Ora>12:00:00</Ora>
          <Luogo>Padova</Luogo>
          <Prenotazioni>
            <!-- nessuna prenotazione -->
          </Prenotazioni>
        </Partenza>
        <Tappa Numero="1">
          <PostiDisp>3</PostiDisp>
          <!-- il num di posti disponibili dev essere coerente con : PostiTot-count(Prenotazioni/Utente) -->
          <Data>2016-04-24</Data>
          <Ora>15:00:00</Ora>
          <Luogo>Vicenza</Luogo>
          <Prenotazioni>
            <Utente>u2</Utente>
          </Prenotazioni>
        </Tappa>
        <Tappa Numero="2">
          <PostiDisp>3</PostiDisp>
          <!-- il num di posti disponibili dev essere coerente con : PostiTot-count(Prenotazioni/Utente) -->
          <Data>2016-04-24</Data>
          <Ora>16:00:00</Ora>
          <Luogo>Padova</Luogo>
          <Prenotazioni>
            <Utente>u2</Utente>
          </Prenotazioni>
        </Tappa>
        <Arrivo Numero="4">
          <PostiDisp>4</PostiDisp>
          <Data>2016-04-24</Data>
          <Ora>17:00:00</Ora>
          <Luogo>Padova</Luogo>
          <Prenotazioni>
				</Prenotazioni>
        </Arrivo>
      </Itinerario>
      <Bacheca>
        <!-- il "destinatario" della conversazione è sempre il conducente del viaggio, identificato da User2  -->
        <!-- il mittente è sempre user 1 -->
        <!-- il conducente non può inserire un messaggio bacheca che non sia risposta a una conversazione esistente -->
        <ConversazioneBacheca User1="u2" User2="u1">
          <Messaggio>
            <Mittente>u2</Mittente>
            <Data>1999-11-11</Data>
            <Ora>12:00:00</Ora>
            <Testo> soma text </Testo>
          </Messaggio>
          <Messaggio>
            <Mittente>u1</Mittente>
            <Data>1999-11-11</Data>
            <Ora>12:00:00</Ora>
            <Testo> soma text inviato da conducente</Testo>
          </Messaggio>
          <Messaggio>
            <Mittente>u2</Mittente>
            <Data>1999-11-11</Data>
            <Ora>12:00:00</Ora>
            <Testo> soma text </Testo>
          </Messaggio>
          <Messaggio>
            <Mittente>u1</Mittente>
            <Data>1999-11-11</Data>
            <Ora>12:00:00</Ora>
            <Testo> soma text inviato da conducente</Testo>
          </Messaggio>
        </ConversazioneBacheca>
      </Bacheca>
    </Passaggio>
  </SetPassaggi>
  <!--  ***************************************************************   SET MESSAGGI   ************************** -->
  <SetMessaggi>
    <Conversazione User1="u2" User2="u1">
      <Messaggio Letto="no">
        <Mittente>u2</Mittente>
        <Data>2016-04-24</Data>
        <Ora>18:07:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
      <Messaggio Letto="si">
        <Mittente>u1</Mittente>
        <Data>2016-04-24</Data>
        <Ora>19:07:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
      <Messaggio Letto="no">
        <Mittente>u2</Mittente>
        <Data>2016-04-24</Data>
        <Ora>19:10:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
      <Messaggio Letto="no">
        <Mittente>u2</Mittente>
        <Data>2016-04-24</Data>
        <Ora>19:10:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
      <Messaggio Letto="no">
        <Mittente>u2</Mittente>
        <Data>2016-04-24</Data>
        <Ora>19:10:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
      <Messaggio Letto="no">
        <Mittente>u2</Mittente>
        <Data>2016-04-24</Data>
        <Ora>19:10:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
      <Messaggio Letto="no">
        <Mittente>u2</Mittente>
        <Data>2016-04-24</Data>
        <Ora>19:10:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
      <Messaggio Letto="si">
        <Mittente>u1</Mittente>
        <Data>2016-04-24</Data>
        <Ora>11:07:00</Ora>
        <Testo> [.............] </Testo>
      </Messaggio>
    </Conversazione>
  </SetMessaggi>
  <!--  ***************************************************************   SET FEEDBACK   ************************** -->
  <SetFeedback>
    <Feedback IDMitt="u1" IDDest="u2">
      <Passaggio>v1</Passaggio>
      <Commento>Viaggio tranquillo</Commento>
      <ValutazionePasseg>
        <PunteggioMedio>4</PunteggioMedio>
        <Compagnia>3</Compagnia>
        <Puntualita>2</Puntualita>
      </ValutazionePasseg>
    </Feedback>
    <Feedback IDMitt="u2" IDDest="u1">
      <Passaggio>v1</Passaggio>
      <Commento>Commento facoltativo</Commento>
      <ValutazioneConduc>
        <PunteggioMedio>3</PunteggioMedio>
        <Compagnia>3</Compagnia>
        <Puntualita>3</Puntualita>
        <Pulizia>3</Pulizia>
        <Guida>3</Guida>
      </ValutazioneConduc>
    </Feedback>
  </SetFeedback>
</ts:TravelShare>
